### ISSUE TITLE
Clarity Decentralized Stacking Pool 

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#278]
## Background
- Pure stacking pool in Clarity.
- It was decided that voting happens in the stacking pool as well
- Managed by `sbtc-controller`

## Key Contract Features

- Updating/Maintaining peg/threshold wallet state
- Trigger asset movements
- Stacker pre/registration 
- Tracks reward cycles
- Submitting/Voting on next peg wallet address

## Definition
What is accomplished in this project? What is the definition of done?
## Motivation
Why is this project important?
## Technical Risk
Why would this project be delayed or impossible?
## Dependencies
We have to collaborate with a Stacks Grant (CB-2Q23-02.1 : Decentralized Stacking Pool https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/871) granted to @BowTiedDeployer.

## Rough implementation plan & timeline
Which main sub-deliveries are part of this project? How can we track and measure the progress?
When do we expect this to be completed?
Consider voting logic is worth stripping out

1. Cycle Tracking
With no dependents outside of querying burn-blockchain for height, a simple but useful first feature could be keeping track of the cycle (aka which phase we’re in).

2. Stacking-Pool Early Features
A subset of the stacking-pool.clar features, such as delegation, submitting addresses & voting on addresses are all also features not heavily dependent on other contracts. 

3. Updating Peg/Threshold State
Since a “bad peg” can occur throughout all phases & be thrown by any vigilante, it’s likely we’ll need close to full functionality across all feature sets to guarantee we cover all penalization scenarios.

**Comment by igorsyl** [comment]
@jo-tm please review pre-existing work: https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/871

**Comment by setzeus** [comment]
@igorsyl have made some progress here I'm pushing likely tomorrow end of date. Will reach out to @BowTiedDeployer to catch up on their progress.

**Comment by friedger** [comment]
Fast pool is in production. Happy to chat

**Comment by setzeus** [comment]
Yeap, I've been reading through it & Xverse too. Only question I had was the (allow-contract-caller ...) func - that is extraneous right? Didn't see anyone call it from the production contract & reading through pox-2 I gathered that tx-sender is supposed to call *pox-2* with pool contract as the param to set that permission.

Since that permission is set in pox-2, the local (check-contract-caller ...) basically only asserts that tx-sender == contract-caller right?

**Comment by friedger** [comment]
allow-contract-caller is to further protect users' stacking rights.
Without that, users could unknownly give permission to a different pool or so.

**Comment by friedger** [comment]
What is the reason for the decision "that voting happens in the stacking pool as well". Normally, the stacking pool can be the same for all pools, only the reward distributions contract would read data from stacking pool contract and set the pox-address.

**Comment by setzeus** [comment]
The core reason is to incentivize the stackers (signers) to maintain the sBTC-mini peg. This translates to the life-cycle of this particular stacking pool being highly-dependent/tightly-coupled with both the state of .sbtc-controller & the voting process. Some examples of this mechanism are:

1. The pool itself can't/shouldn't be able to "delegate-stack-stx" until the next cycle threshold-wallet has been elected (ie - the wallet decided upon by winning 70% of the vote).

2. The pool itself should stop/extend/punish the current stackers/signers if they fail to transfer the peg-balance from the current threshold wallet to the next threshold wallet.

3. If any other contract in the sbtc-mini protocol (controller, peg-in, peg-out, asset, or btc-verification) causes a bad peg-state then the pool needs to know / react accordingly.

I'm still not entirely sure that I can't/shouldn't strip out the voting from the pool (I'll revisit once the WIP is done), but regardless we can't strip out *all* relevant sbtc-mini logic from the pool since it'd remove the peg incentive.

**Comment by friedger** [comment]
The current stacking pool contract has an active flag that is controlled by the reward admin.
Would that be enough to solve 1., 2. and 3. if the reward admin is the controller?

It would be nice if the peg incentive is manifested in that flag. I think that this makes the protocol easier to understand for pool members.

**Comment by jo-tm** [comment]
@friedger can we meet with @setzeus to discuss which logic we can take out of the pool and which logic we cannot?

**Comment by friedger** [comment]
@jo-tm When? Where?

**Comment by igorsyl** [comment]
@jo-tm @friedger Let's use Discord to coordinate meetings.

**Comment by jo-tm** [comment]
Add the full Clarity WG to the meeting with @friedger if possible @igorsyl

**Comment by jo-tm** [comment]
Jesus branched Marvin Peg-In branch. Started writing the Clarity tests. Blocker: running into `prepare` problems with clarity tests. Depends on Pox-2.

**Comment by jo-tm** [comment]
- Update commits here on branch: https://github.com/Trust-Machines/core-eng/commits/sbtc-mini-staking-pool-and-peg-transfer

**Comment by setzeus** [comment]
PR Review submitted which includes 1st draft of both stacking pool & peg-transfer/handoff contracts: https://github.com/Trust-Machines/core-eng/pull/377

**Comment by jo-tm** [comment]
- post any updates if applicable here.
- @setzeus  please plan for Date Completion to be 16th June or June or 30th June (or earlier), use the **Week** field. So we have 2-week Sprint Granularity for June and not 1 week that is too tight. Also, add an **Estimation of #Days** for @igorsyl Gantt if you want.

**Comment by jo-tm** [comment]
Updates on PR.
