### ISSUE TITLE
Format Clarity to have 1 Line per Exec Branch

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#305]
Because the coverage tool considers lines and not branches, if we have at least one line per branch we can cover branches using the lines.

Add this to CI of `sbtc-mini`.

**Comment by jo-tm** [comment]
friedger forked from this formatter for Lisp that has a bug in the comments (spaces are removed), not sure if it has any other bugs:

Repo: https://github.com/imjacobclark/vscode-lisp-formatter

```clarity
(define-private (set-protocol-iter (entry {contract: principal, enabled: bool}))
	(and
		;; Only contract principals can be part of the protocol
		(is-some (get name (unwrap! (principal-destruct? (get contract entry)) false)))
		(map-set privileged-protocol-principals (get contract entry) (get enabled entry))
	)
)
```

Formatted:

```clarity
(define-private 
    (set-protocol-iter 
        (entry {contract: principal, enabled: bool}))
    (and
;;Onlycontractprincipalscanbepartoftheprotocol
        (is-some 
            (get name 
                (unwrap! 
                    (principal-destruct? 
                        (get contract entry)) false)))
        (map-set privileged-protocol-principals 
            (get contract entry) 
            (get enabled entry))
)
)
```

**Comment by MarvinJanssen** [comment]
Auto-formatting will help but it won't be perfect. Even in the above examples you can see that the `unwrap!` short circuit branch is on the same line as the `get`.

One line per logical branch would be best but if that is too tricky to figure out (you'd have to analyse the source instead of just counting brackets) then we can also do it the "dumb" way and just put every atom / s-expression on a separate line.

Best, of course, would be if Clarinet can provide coverage info per logical branch from the onset.

**Comment by njordhov** [comment]
This should be called _**Uglify**_

**Comment by njordhov** [comment]
To accommodate test tooling, the Clariform linter/formatter can format Clarity with a single line per branch/expression, or split each expression over multiple lines. https://github.com/PromptECO/clariform/issues/23

**Comment by jo-tm** [comment]
Jose will explore Clariform and ask Sergey if need to conform with any CI standard.

**Comment by jo-tm** [comment]
You should get an error in the CI when pushing code that is not properly formatted.

**Comment by jo-tm** [comment]
Discussed with Marvin that if is part of CI will not stop the devs to push.

**Comment by njordhov** [comment]
I suggest Clariform is used as a preprocessor before codecov/testing rather than require the Clarity code in the repo to have a hard to read formatting. Clariform can also prettify Clarity with auto-indent and has a `strict` option that can be used to ensure proper and readable formatting of Clarity in the repo. See workflows for examples of how to set Clariform up as a github action: https://github.com/PromptECO/clariform/tree/main/.github/workflows

**Comment by jo-tm** [comment]
No updates.

**Comment by jo-tm** [comment]
- Included in CI via `test.sh`.
- Will post an example to confirm that the spreading is not too much or too little.

**Comment by jo-tm** [comment]
- Resend PR Review Req if needed.

**Comment by MarvinJanssen** [comment]
Looks fine to me, it will help until Clarinet can do coverage per branch.

**Comment by lgalabru** [comment]
You've been served! https://github.com/hirosystems/clarinet/pull/1030

**Comment by jo-tm** [comment]
thanks a lot @lgalabru !

**Comment by jo-tm** [comment]
No updates.
