### ISSUE TITLE
Stacks node is not aware of any sBTC operations in blocks that it didn't process itself

### ISSUE THREAD

**Issue by stjepangolemac** [Trust-Machines/stacks-sbtc#456]
1. Download an archive from Hiro
2. Run the stacks-node
3. stacks-node is not aware of any sBTC operations from blocks in the archive, it will only properly process blocks not contained in the archive

#### Proposal

- Split the current get ops RPC calls into 2 phases
- See if a specific block was processed for sBTC operations
- If it was, return the operations
- If it wasn't, get the block, process it, store sBTC ops, return them

**Comment by stjepangolemac** [comment]
cc @netrome

**Comment by netrome** [comment]
To clarify, the issue here is that since the non-alpha nodes are not aware of sBTC - the hiro archive naturally does not contain any sBTC op data.

While extending the querying logic in the stacks node is one solution, another route which would not require any stacks changes would be for us to write a CLI tool to extract sBTC ops from a given range of bitcoin blocks. These could be injected in our sortition database before restarting a node when recovering from an archive, or alternatively we could maintain a sBTC-alpha archive in a GCS bucket somewhere where we clone the hiro archive and augment it with this info.

**Comment by stjepangolemac** [comment]
The CLI tool would ultimately need to do the same thing as the get ops RPC calls. If the required effort is equal for both solutions I believe having it included in the node has the most value. On the other hand, it might be hard to collaborate, get required feedback and reviews on time, when working in the stacks-blockchain repo.

**Comment by netrome** [comment]
Yeah, my (very minor) concerns about introducing this in the Stacks node is twofold:

1. It could be much more complex than introducing it as a standalone tool. This depends on how easy it is to make arbitrary bitcoin node RPC calls from the Stacks code, which I don't know. This could be trivial, or require big code reorgs. Definitely worth looking into.

2. This is a temporary workaround, which we will remove in the final release. We'd have to both introduce it and remove it if we run it within the node. If it's a separate tool we just deprecate it once we're done. It could also still be useful for debugging properties and other purposes.

These are not big issues, so it's worth looking into this solution. But if it turns out to be a big hairball, we have other options to solve this problem.

**Comment by stjepangolemac** [comment]
Yes I agree, we need to check how hard it is to talk with the Bitcoin node.

On the other hand, I'm not sure we'd need to remove this later. I see two approaches:
1. Remove this later - means we rely on implicit knowledge of the minimum block where we can expect sBTC ops, first block with an actual sBTC op, etc
2. We keep this and rely on the process - works regardless of block height, when the nodes upgraded, no implicit dependencies that we need to worry about

**Comment by netrome** [comment]
Sure if the implementation turns out to be clean it could be a nice fallback to keep. The only problem I see is that it would slow down queries to block heights without sBTC ops.

**Comment by stjepangolemac** [comment]
Moved to the main GitHub organization https://github.com/stacks-network/stacks-blockchain/issues/3840
